### ISSUE TITLE
Update Heap code

### ISSUE THREAD

**Issue by scottweisman** [CuresWithinReach/CureAccelerator#5]
The Heap analytics code isn't working. Probably caused by copy and pasting from an email? Here's the code again: 

<script type="text/javascript">
  window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+t+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
  heap.load("2646777590");
</script>

**Comment by kurtcunningham** [comment]
Can you paste that code again, @scottweisman. Didn't show up.
